% CSCounsellingSD  (nfr3 dialect: <-- rules, soft bodies are edges)
:- discontiguous (<--)/2.
:- dynamic (<--)/2.
goals(hard) <--
  [ counsellingPoliciesBeFollowed,
    allowUserToLogIn,
    itSystemsBeIntegrated,
    allowUserToLogIn1,
    trainingBeReceived ].
goals(soft) <--
  [ or([ considerationOfFeedbackManagers,
         controlOfCounsellingWork,
         improveQualityAssuranceTechnology,
         csStories,
         empoweringKidsToHelpThemselves,
         currentResourceLinks,
         increasedCautionContentOfOnlineServices,
         decreaseClumsinessTechnology,
         voiceCounselling,
         accessibleResourcesForCounselors1,
         improvedWritingSkillsCounsellors,
         facilitateFasterChangesInCounsellorDuties,
         easilyAccessableTechnologyInstructions,
         currentResourceLinks1,
         avoidDialoguesWebServices,
         patientCounselor,
         improveITSkills,
         professionalWorkEnvironment,
         reduceNumberOfStepsWebPostingTechnology,
         anonymityCounsellors,
         increaseITMethodsToAcquireFeedback,
         reduceContagionEffectOfHarmfulActions,
         performCounsellingAsInstructedBySupervisor,
         accommodateSchedules,
         avoidLiabilityProblems,
         helpKids,
         simpleTechnology,
         highDegreeOfSimilarityBetweenServicesProvided,
         completeResourceLinks,
         accessibleResourcesForCounselors,
         acquirePublicSpeakingSkills,
         consistentResourceLinks,
         helpAsManyKidsAsPossible,
         accessibleResourcesForCounselors2,
         webResponsesBeGeneric,
         recognition,
         salary,
         reducePrankCalls,
         correctInterpretationOfCounsel,
         accountabilityOfServices,
         considerationOfFeedbackITProviders,
         improveITSkills1,
         easierToFindPostsWebPostingTechnology,
         highQualityResources,
         increaseCSAwareness,
         effectiveUseOfTechnologyCounsellors,
         helpAsManyKidsAsPossible1,
         completeResourceLinks1,
         improveCallRecordingEquipment,
         reduceStaggeringOfSchedules,
         highQualityCounselling1,
         increaseITTrainingForCounsellors,
         happinessCounsellors,
         increaseNumberOfCounsellors,
         highQualityCounselling,
         avoidRelationshipsWithSpecificCounsellor,
         clearerCallClassificationCatagories,
         rememberLocationsOfResouces,
         increaseEmphasisOnOnlineFeedbackForm,
         improveCounsellingSkills,
         increasedPeerSupport ]) ].
avoidRelationshipsWithSpecificCounsellor <-- [voiceCounselling].
callerStatistics <-- [voiceCounselling].
diffuseConflictWithParent <-- [voiceCounselling].
voiceCounselling <--
  [ allowUserToLogIn1,
    implementCategorizationTool,
    allowUserToLogIn ].
voiceCounsellingBePerformed <-- [voiceCounselling].
voiceCounsellingBePerformed1 <-- [voiceCounselling].
